# Generated by Django 2.0.4 on 2018-06-20 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tadu_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=300)),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join date'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
